[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/*.jsx.1"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/*.js.1"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[build]
  functions = "netlify/functions"
  
[dev]
  functions = "netlify/functions"
